/* Generated by Together */

#include "Achtung.h"
#include "../StateFactory.h"

void Achtung::umschalten(StateAmpel * const This){
    fireTransition(This, StateFactory::getFactory()->getState(ANHALTEN));
}
void Achtung::entry(StateAmpel * const This){
    // hier einen blinken Thread starten
    schalteLampen (This, false, true, false);
}
void Achtung::aus(StateAmpel * const This){
    fireTransition(This, StateFactory::getFactory()->getState(AUS));
}
void Achtung::warne(StateAmpel *const){  }
