/* Generated by Together */

#include "Anhalten.h"
#include "../StateFactory.h"

void Anhalten::umschalten(StateAmpel * const  This){
    fireTransition(This, StateFactory::getFactory()->getState(STEHEN));
}
void Anhalten::entry(StateAmpel * const This){
    schalteLampen (This, false, true, false);
}
