/* Generated by Together */

#include "Aus.h"
//#include "../Lampe.h"
void Aus::aus(StateAmpel * const This){ }
void Aus::entry(StateAmpel * const This){
	//(This->*rot)->aus();
    schalteLampen (This, false, false, false);
}
