/* Generated by Together */

#include "StartVorbereiten.h"

void StartVorbereiten::umschalten(StateAmpel * const This){
	fireTransition(This, getState(FAHREN));
}
void StartVorbereiten::entry(StateAmpel * const This){
 schalteLampen(This, true, true, false);
}
