/* Generated by Together */

#include <iostream>
using namespace std;

#include "IPLampe.h"

IPLampe::IPLampe(string ipAdress) : an(false), ipAdress(ipAdress)
{
	cout << "IPLampe(): " << ipAdress << endl;
}
bool IPLampe::isAn(){ return an;}

void IPLampe::ein(){
    //hier die kommunikation mit der HW-Lampe realisieren
    an = true;
    cout << ipAdress << " ";
}
void IPLampe::aus(){
    //hier die kommunikation mit der HW-Lampe realisieren
    an = false;
    //cout << ipAdress << " aus ";
}
